akka {
  actor {
    provider = cluster

    serialization-bindings {
      "it.unibo.agar.Message" = jackson-cbor
    }
  }
  remote {
    artery {
      canonical.hostname = "127.0.0.1"
      canonical.port = 0
    }
  }
  cluster {
    seed-nodes = [
       "akka://agario@127.0.0.1:2551"
     ]
    downing-provider-class = "akka.cluster.sbr.SplitBrainResolverProvider"
  }

  cluster.split-brain-resolver {
    active-strategy = keep-oldest

    keep-oldest {
      down-if-alone = off
      role = "main"
    }
  }
}
akka.cluster.jmx.multi-mbeans-in-same-jvm = on