my-blocking-dispatcher {
  type = Dispatcher
  executor = "thread-pool-executor"
  # Configuration for the thread pool
  thread-pool-executor {
    core-pool-size-min = 2
    core-pool-size-max = 64
  }
  throughput = 1
}